[package]
name = "nbody"
version = "0.1.0"
authors = ["wullewutz <wullewutz@users.noreply.github.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
ggez = "0.5"
rand = "0.7"
assert_approx_eq = "1.1.0"
itertools = "0.8"