[package]
name = "nbody"
version = "0.1.0"
authors = ["wullewutz <wullewutz@users.noreply.github.com>"]
edition = "2021"

[dependencies]
structopt = "0.3"
ggez = "0.7"
rand = "0.8"
assert_approx_eq = "1.1.0"
itertools = "0.10"
glam = { version = "0.20", features = ["mint"]}

